language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.10.x
  - 1.9.x

matrix:
  fast_finish: true

services:
  - docker

before_install:
  - docker pull redislabs/rejson
  - docker run -d -p 6379:6379 --name redis-rejson redislabs/rejson:latest
  - docker ps -a
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5

install:
  - env GO111MODULE=on go get ./...

script:
  - env GO111MODULE=on go test -v . -covermode=count -coverprofile=profile.cov .
  - env GO111MODULE=on golangci-lint run ./...

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci

